---

##
# Prerequisites
##

- name: Unsupported operating system
  fail: msg='This role requires a RedHat or Ubuntu based operating system'
  when: ansible_os_family != "RedHat" and ansible_os_family != "Debian"

- name: Setup repos (yum)
  yum:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

##
# Install
##

- name: Install packages and dependencies (apt)
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_apt }}"
  when: ansible_os_family == "Debian"

- name: Install packages and dependencies (yum)
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages_yum }}"
  when: ansible_os_family == "RedHat"

##
# Configure
##

- name: Copy index.html (Debian)
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == "Debian"

- name: Copy index.html (RedHat)
  template:
    src: index.html.j2
    dest: /usr/share/nginx/html/index.html
    owner: root
    group: root
    mode: '0755'
  when: ansible_os_family == "RedHat"


##
# Service Management
##

- name: Enable and start services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items: "{{ services }}"
